steps:
- name: ubuntu
  args: ['bash', '-c', "echo '$COMMIT_SHA' > REVISION.txt"]
- name: gcr.io/cloud-builders/gsutil
  args:
    - '-m'
    - 'rsync'
    - '-d'
    - '-r'
    - 'dags'
    - 'gs://${PROJECT_ID}/script_submit_spark/api-gcp-gov-br/submit_file_config.py'
options:
  logging: CLOUD_LOGGING_ONLY
